[2022-05-03 05:51:54,255] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_streamers_eSports.ML_Pipeline_Half manual__2022-05-03T05:43:23.443699+00:00 [queued]>
[2022-05-03 05:51:54,331] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_streamers_eSports.ML_Pipeline_Half manual__2022-05-03T05:43:23.443699+00:00 [queued]>
[2022-05-03 05:51:54,331] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-03 05:51:54,331] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-03 05:51:54,331] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-03 05:51:54,447] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): ML_Pipeline_Half> on 2022-05-03 05:43:23.443699+00:00
[2022-05-03 05:51:54,452] {standard_task_runner.py:52} INFO - Started process 30815 to run task
[2022-05-03 05:51:54,456] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_streamers_eSports', 'ML_Pipeline_Half', 'manual__2022-05-03T05:43:23.443699+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp8c4ovvip', '--error-file', '/tmp/tmp95oa5lpz']
[2022-05-03 05:51:54,457] {standard_task_runner.py:80} INFO - Job 34: Subtask ML_Pipeline_Half
[2022-05-03 05:51:54,771] {task_command.py:369} INFO - Running <TaskInstance: ETL_streamers_eSports.ML_Pipeline_Half manual__2022-05-03T05:43:23.443699+00:00 [running]> on host cube-14ce9f9c-b3e2-4031-af90-157b53c1fe85-669c6656fd-gv56j
[2022-05-03 05:51:55,264] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ETL_streamers_eSports
AIRFLOW_CTX_TASK_ID=ML_Pipeline_Half
AIRFLOW_CTX_EXECUTION_DATE=2022-05-03T05:43:23.443699+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-03T05:43:23.443699+00:00
[2022-05-03 05:51:55,286] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda/envs/Python3/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda/envs/Python3/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/project/airflow_home/dags/etl_dag.py", line 242, in ml_training
    logmodel = LogisticRegression(max_iter = 10000)
NameError: name 'LogisticRegression' is not defined
[2022-05-03 05:51:55,348] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=ETL_streamers_eSports, task_id=ML_Pipeline_Half, execution_date=20220503T054323, start_date=20220503T055154, end_date=20220503T055155
[2022-05-03 05:51:55,465] {standard_task_runner.py:92} ERROR - Failed to execute job 34 for task ML_Pipeline_Half (name 'LogisticRegression' is not defined; 30815)
[2022-05-03 05:51:55,508] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-03 05:51:55,653] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
