[2022-05-01 22:24:32,528] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_streamers_eSports.Extract manual__2022-05-01T22:14:18.361552+00:00 [queued]>
[2022-05-01 22:24:32,598] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: ETL_streamers_eSports.Extract manual__2022-05-01T22:14:18.361552+00:00 [queued]>
[2022-05-01 22:24:32,598] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-01 22:24:32,599] {taskinstance.py:1357} INFO - Starting attempt 3 of 3
[2022-05-01 22:24:32,599] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-01 22:24:32,713] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): Extract> on 2022-05-01 22:14:18.361552+00:00
[2022-05-01 22:24:32,717] {standard_task_runner.py:52} INFO - Started process 20609 to run task
[2022-05-01 22:24:32,720] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_streamers_eSports', 'Extract', 'manual__2022-05-01T22:14:18.361552+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpp0wrvjk1', '--error-file', '/tmp/tmplslsm9uw']
[2022-05-01 22:24:32,721] {standard_task_runner.py:80} INFO - Job 17: Subtask Extract
[2022-05-01 22:24:33,015] {task_command.py:369} INFO - Running <TaskInstance: ETL_streamers_eSports.Extract manual__2022-05-01T22:14:18.361552+00:00 [running]> on host cube-14ce9f9c-b3e2-4031-af90-157b53c1fe85-669c6656fd-gv56j
[2022-05-01 22:24:33,390] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ETL_streamers_eSports
AIRFLOW_CTX_TASK_ID=Extract
AIRFLOW_CTX_EXECUTION_DATE=2022-05-01T22:14:18.361552+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-01T22:14:18.361552+00:00
[2022-05-01 22:24:33,391] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda/envs/Python3/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda/envs/Python3/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/project/airflow_home/dags/etl_dag.py", line 52, in extract
    online_rn = extract_funcs.get_streamers('online')
  File "/project/airflow_home/dags/custom_package/extract_funcs.py", line 9, in get_streamers
    sys.setrecursionlimit(100000)
NameError: name 'sys' is not defined
[2022-05-01 22:24:33,437] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=ETL_streamers_eSports, task_id=Extract, execution_date=20220501T221418, start_date=20220501T222432, end_date=20220501T222433
[2022-05-01 22:24:33,548] {standard_task_runner.py:92} ERROR - Failed to execute job 17 for task Extract (name 'sys' is not defined; 20609)
[2022-05-01 22:24:33,573] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-01 22:24:33,815] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
